### ISSUE TITLE
AdlibBlasterx64 0.11.1 (AudioUnit) has digital noise upon start with DOSBox emulation only

### ISSUE THREAD

**Issue by douglas-carmichael** [bsutherland/JuceOPLVSTi#34] opened 2016-01-11 05:55 UTC
System: Logic Pro X 10.2.0, AdlibBlasterx64 0.11.1.

When I start playing a project with the DOSBox emulation, there is a burst of digital noise (then the project starts playing). But, when I use the ZDoom emulation, there is no noise burst and the project plays as normal.
Attached is a ZIPed WAV file.

[Adlib_DOSBox_DigiNoise.zip](https://github.com/bsutherland/JuceOPLVSTi/files/85348/Adlib_DOSBox_DigiNoise.zip)

**Comment by bsutherland** [comment] 2016-01-11 08:09
Douglas, thanks for the detailed report. Unfortunately I don't have a Mac so I have no way to build or test on OSX :(

You could try reporting the issue to Jeff Russ who built the AudioUnit version.

https://github.com/Jeff-Russ/AdlibBlaster

Cheers.

**Comment by razvanab** [comment] 2016-02-06 20:22
The same thing happens but the noise persist until i switch to ZDoom  in windows when i use this vst with vsthost from
http://www.hermannseib.com/english/vsthost.htm

**Comment by bsutherland** [comment] 2016-02-07 05:26
Thanks for the extra info razvanab.

**Comment by Jeff-Russ** [comment] 2016-02-07 07:17
Everybody: I'm consumed in a web development project at the moment but I plan to return and fix the Mac build as soon as I can. Sorry I've been AWOL!!

**Comment by razvanab** [comment] 2016-02-07 13:45
I don't know if this is the right place to post this but i found out how to fix the noise in vsthost from:
http://www.hermannseib.com/english/vsthost.htm

In select Wave devices  you need to set the buffer as low as possible.

**Comment by Jeff-Russ** [comment] 2016-02-08 04:50
@douglas-carmichael  @razvanab 
This is by no stretch a "release" but I had some free time to I fired up Xcode. I just made a few changes and it compiled. It ran with no __major__ issues in OSX 10.10 Logic Pro X and OSX 10.10 Ableton Live 9 as both AUi and VSTi. I _didn't test it very much_ but see if this fixed whatever issue you had... 

[Download AUi](https://s3.amazonaws.com/adlibblaster/osx/JuceOPL-vst_Jeff-Russ_build160207.zip)
[Download VSTi](https://s3.amazonaws.com/adlibblaster/osx/JuceOPL-au_Jeff-Russ_build160207.zip)
[my fork of JuceOPLVSTi](https://github.com/Jeff-Russ/AdlibBlaster)

**Comment by bsutherland** [comment] 2016-02-09 13:22
Thanks razvanab! That might help me track it down.

I'll also put it in the wiki.

**Comment by jeremypenner** [comment] 2016-03-29 02:37
It looks like the problem is in `DBOPL::Handler::Generate` - if it's asked to generate more than 512 samples, it only puts 512 samples in the buffer, then stops.  No idea what that logic is for, but if I comment it out, the noise appears to go away.

(Using GarageBand as an AU host for testing.)

I can put together a real pull request if that helps, but it seems to be a very simple fix.

**Comment by bsutherland** [comment] 2016-03-29 21:59
Jeremy, that sounds very promising! That would explain the issue at higher sample rates in some hosts. Thanks a lot for finding the issue and letting me know!!

I'll try to put out a new build within a week.

**Comment by bsutherland** [comment] 2016-05-14 12:41
This issue *might* be fixed in the latest Windows release. Closing this issue for now as there are many similar tickets.

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.1

**Closed by bsutherland** 2016-05-14 12:41 UTC
