### ISSUE TITLE
Building OSX version (AudioUnit under XCode)

### ISSUE THREAD

**Issue by ghost** [bsutherland/JuceOPLVSTi#12] opened 2013-12-09 05:09 UTC
I did a test build under Xcode 5.0.2, and get the error "cast from pointer to smaller type 'Bitu' loses information" on lines 1443 and 1458 of dbopl.cpp. Also the error  "use of undeclared identifier 'fmod' on line 62 of adlib.h. I haven't dug any deeper yet.

**Comment by Jeff-Russ** [comment] 2015-02-11 01:59
I there anywhere I can download the source for the Mac build? There is a lot of platform specific stuff in the original JuceOPLVSTi that prevent it from building and/or result in incorrect number of bits in Xcode. The right solution would be modify the source so that it builds on any platform without tinkering (that's what Juce is for!). I started to modify the original with this goal... not knowing someone else already made a binary for Mac.

**Comment by bsutherland** [comment] 2015-02-11 06:42
Hi Jeff,

As far as I know, so far nobody has successfully built an OSX version that works correctly. Sorry about the platform specific stuff. I'm afraid that I don't have a Mac, so I can't really help. I (and a lot of others!) would be very grateful if you manage to build it for OSX though! If you do, please push your code and send me the binary!

Bruce

**Comment by Jeff-Russ** [comment] 2015-02-11 16:41
Okay, I'm on it. gimme a week or so.

**Comment by Jeff-Russ** [comment] 2015-02-12 02:30
32-bit AUi build: succeeded, 64-bit AUi build: succeeded. I don't hear any audio problem and the gain is quite high, although this is a pretty hack solution so I'm not confident there aren't some hidden issues. I'll hang on to these binaries and clean up the code before I push it. If you want the binary now I can send it your way.

**Comment by bsutherland** [comment] 2015-02-12 02:33
Great work! Thanks a lot. I'll wait until you've finished what you want to do on the code and played with it a bit more, then upload the binaries.

**Comment by nrezmerski** [comment] 2015-02-13 02:28
That's awesome, Jeff! Can you tell us briefly what you changed to compile it? Thanks.

**Comment by Jeff-Russ** [comment] 2015-02-13 03:25
Thanks! I added the Xcode exporter to the introjucer of course. Its only set to build for VSTi on Mac (32 or 64-bit work) at the moment as a tweak the AU build. Missing functions and types found in windows.h are now supplemented with replacements.  Typedefs that depend on compiler-specific implementation were replaced with more predictable ones.

**Comment by nrezmerski** [comment] 2015-02-13 05:04
Jeff, here's the current location of my last attempt: http://nick.rezmerski.com/code/

**Comment by Jeff-Russ** [comment] 2015-02-20 16:54
bsutherland, It's done. I just have to go home, which I never am, to my newer Mac desktop to build it with the newer OS X Frameworks. Expect it in a few days.

**Comment by bsutherland** [comment] 2015-02-20 23:04
Jeffrey, thank you very much for your efforts! I just started a new job
where we're using OS X, so I'll try it out :)

**Comment by Jeff-Russ** [comment] 2015-02-21 00:42
Congrats! All politics aside, OS X is an excellent environment for musician-programmers. The Core Audio API is basically given kernel-level priority and, in spite of what people think, it's a pretty open system... maybe not as much as Linux but more than Windows. 

If you ever need some OS X help I'd be down; working on this OPLVSTi project has helped me a lot.

Next I'd like to work on making JuceOPL work with Linux under Bitwig and possibly make and iOS app if that sounds alright to you. The "VSTi" part of the name will hardly make sense at that point.

**Comment by nrezmerski** [comment] 2015-02-21 02:52
Just a word of warning on the iOS app - the App Store terms of use conflict with the GPL license, which covers most of the JUCE modules. Of course, you can buy a commercial JUCE license if you want to sell the app.

The DOSBox and ZDoom code are LGPL. See: https://www.fsf.org/news/2010-05-app-store-compliance and http://stackoverflow.com/questions/459833/which-open-source-licenses-are-compatible-with-the-apples-iphone-and-its-offici

**Comment by Jeff-Russ** [comment] 2015-02-21 03:57
I'm aware. It would be an app for jailbroken iOS.

**Comment by bsutherland** [comment] 2015-02-21 07:33
Jeffrey, thanks for the offer of future help on OS X! There was a request
for a Linux version, so I'm sure your work would be appreciated:
https://github.com/bsutherland/JuceOPLVSTi/issues/21

I'm a bit busy at the moment with the new job but will merge your code and
rebuild on Windows soon. Looking forward to receiving the binary, but no
rush.

I have no objections to an iOS app. If you could link back the original
project that would be great. Would you be porting it to Objective C, or is
there another way? Are there C++ compilers for jailbroken iOS devices?
About the name.. I've been considering renaming it for a while now :) It's
a real mouthful. So far the only idea I've come up with is "Ad Lib
Platinum". Any suggestions?

I actually really like OS X as an operating system for development so far.
Only thing I don't like is that hardware choice is limited if you want to
run it legally.

Nick: The DOSBox code is GPL'd too, so nobody can sell this plugin or a
derivative even if they purchase a JUCE license.

**Comment by nrezmerski** [comment] 2015-02-21 08:48
Actually, you CAN sell it under GPL... you just can't add additional terms to the license. :)

I just looked at opl.h and opl.cpp, which said LGPL, but I see they have GPL on other files.

I know JUCE can target iOS, but I have no idea how much work would be necessary to port the code!

**Comment by Jeff-Russ** [comment] 2015-02-22 18:36
nrezmerski  - A port for iOS would not be as simple as just compiling for iOS but it's definitely doable. Apple does NOT allow ANY GPL code in the app store regardless of whether it's a fee app or not. I'm not sure about the license situation for DOXBox but the emu itself could be rebuilt. My area of expertise is in DSP algorithms and I latched on to this OPLVSTi project to learn the OTHER aspects I was not as good with. I would be interested in rebuilding the audio engine. 

 bsutherland - Apple Core Audio API is and will always be in C++. Apparently the added layer of Juce does not give much or any performance hit in terms of audio processing. The Cocoa and CocoaTouch GUI Frameworks, on the other hand, can only be accessed with Objective-C and Swift, but Juce provides a wrapper for all of that so it's fine to stick with all C++ and with all the sea change going on with Apple Dev I'm happy to keep it C++

SOOO... how the heck do I upload binary to github? I'm new to github. I have working binaries for mac VSTi but AU is still giving me trouble. I'd like to give you what I have so far so we can agree on some sort of cross platform debugging technique that doesn't use windows.h. Shall I just email you the binaries?

**Comment by Jeff-Russ** [comment] 2015-02-22 18:46
P.S. To keep things open source but not have it clash with Apple's corporate concerns. BSD license is the way to go. It's not "viral" like GPL is. Very liberal.

**Comment by nrezmerski** [comment] 2015-02-22 21:21
Jeff, I think you can check out the tree, commit your changes, and create a release in the project if Bruce has added you as a collaborator.

I know Apple can't put GPL'd stuff on the app store, but you could certainly sell the VST or AU plugin as long as you abide by the license terms. I haven't been able to find any OPL stuff under BSD license yet. :(

"AdLib Blaster" is a good straightforward name, but might have trademark issues. I can't think of anything better off the top of my head. JuceFM?
 - Nick

**Comment by Jeff-Russ** [comment] 2015-02-22 21:52
Right. I just mean that for iOS, you pretty much have to go through the app store unless you want to dev for jailbroken iOS. There is already an Adlib Tracker which has no copyright issues as far as I know but Adlib is out of business. Creative still owns the "soundblaster" trademark but I'm certainly sidestepping that one ;) I asked around and more people know "adlib" than than know "OPL" and even more know "soundblaster" but many are not aware that SB16 has an OPL chip in it. Prolly about 0.000001% of people who would use this plugin know what Juce is, nor do they need to.

idunno about the name really... just throwing ideas out.

I don't think i'm a collaborator but I'll try messing around. I still have no idea how to upload a binary without it being linked to the Xcode project file, which causes problems.

**Comment by Jeff-Russ** [comment] 2015-02-23 02:08
Alright, bsutherland, here is is:

http://jeff-russ.github.io/AdLiberator/

**Comment by nrezmerski** [comment] 2015-02-23 02:53
Thanks, Jeff! I haven't tried the VST version but I can't get the AU to load in GarageBand 4 or 10. GB doesn't do VST, but I'll try another host for those.

**Comment by nrezmerski** [comment] 2015-02-23 03:19
I don't know if this will be any help, but Console logged an error trying to load the Audio Unit, saying "Symbol not found: _OBJC_CLASS_$_NSHTTPURLResponse" expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork

**Comment by Jeff-Russ** [comment] 2015-02-23 03:58
What OS X are you on? Are you running GB in 64-bit?

**Comment by nrezmerski** [comment] 2015-02-23 04:17
Mavericks 10.9.5, on an early 2008 2.5Ghz Core Duo MacBook Pro with 4GB of RAM. I also have a Snow Leopard partition, if you compiled for 10.6 compatibility I can try that.

**Comment by Jeff-Russ** [comment] 2015-02-23 04:19
It's not possible to use the updated Juce modules AND older OS X SDKs at once. Apple added stuff to the SDKs that Juce uses. But give it a try anyway...

**Comment by Jeff-Russ** [comment] 2015-02-23 04:26
oh DUH...I misread you. Yeah I compiled it on a new Mac Mini with Yosemite 10.10 using "latest OS" so maybe that's why. I'll try a build for 10.8 since that's when Apple added some stuff to Core Audio.

**Comment by Jeff-Russ** [comment] 2015-02-23 04:38
try this: 
http://bit.ly/1EGV4CQ

**Comment by nrezmerski** [comment] 2015-02-23 05:00
No dice, I still don't see it in either version of GB. I tried downloading Apple's AU Lab as well, and it didn't show up there. I did see the Juce Demo Plugin I compiled a couple days ago.

**Comment by Jeff-Russ** [comment] 2015-02-23 05:01
Weird. I tested it in Ableton Live, Reaper and Logic Pro and it worked fine in all of them. I have no idea...

**Comment by Jeff-Russ** [comment] 2015-02-23 05:14
Yeah I get "plugin failed to load" on my older mac. It's definitely an Apple framework issue too. I'm gonna unpublish the page until I work it out. Thanks for testing!!!

**Comment by nrezmerski** [comment] 2015-02-23 14:31
I managed to build the Juce plugin host demo, which gave me trouble before. I had a lot of errors in the VST3 files, so I just disabled the VST3 features and it compiled. When I ran it, I was able to see your binary plugin, and load it - and it made noise! Multiple instances with no problems. :)

**Comment by Jeff-Russ** [comment] 2015-02-23 16:45
It made noise as in good noise or bad noise? lol

**Comment by nrezmerski** [comment] 2015-02-23 18:57
It sounded good, is what I mean. Not white noise, music. I should have been clear. :)

This is the AU binary you most recently uploaded.

**Comment by Jeff-Russ** [comment] 2015-02-23 19:24
Okay and it still doesn't work in Garage Band?

**Comment by nrezmerski** [comment] 2015-02-23 20:23
That's correct-- Garage Band v.10 and '08 (v.4) don't see it. Here's the auval output:

    AU Validation Tool
    Version: 1.6.1a1 
    Copyright 2003-2013, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'PwAB' - 'Pwve'
--------------------------------------------------
2015-02-23 14:21:45.926 auvaltool[28563:d07] 14:21:45.898 WARNING:   [0x7fff75e53310] >compload> AudioComponentPluginLoader.cpp:662: RegisterComponentsFromArray: 
Manufacturer String: Plainweave Software
AudioUnit Name: AdlibBlaster
Component Version: 0.11.1 (0xB01)
Component's Bundle Version: 0.0.0

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
JUCE v3.1.1

=== Starting debug console.....
Time to open AudioUnit:         2048.391 ms
WARM:

=== Starting debug console.....
Time to open AudioUnit:         147.424  ms
FIRST TIME:
Time for initialization:        0.012 ms

=== Exited debug console ===

* * PASS
--------------------------------------------------
VERIFYING DEFAULT SCOPE FORMATS:
Input Scope Bus Configuration:
 Default Bus Count:0

Output Scope Bus Configuration:
 Default Bus Count:1
    Default Format: AudioStreamBasicDescription:  1 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved

* * PASS
--------------------------------------------------
VERIFYING REQUIRED PROPERTIES:

* * PASS
--------------------------------------------------
VERIFYING RECOMMENDED PROPERTIES:
  VERIFYING PROPERTY: Latency
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:402
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:402
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:402
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:402
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:402
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:402
    PASS

* * PASS
--------------------------------------------------
VERIFYING OPTIONAL PROPERTIES:
  VERIFYING PROPERTY Tail Time
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:408
ca_debug_string: AudioUnitGetProperty: *ioDataSize == 0 on entry /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUDispatch.cpp:178
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:408
ca_debug_string: AudioUnitGetProperty: *ioDataSize == 0 on entry /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUDispatch.cpp:178
ca_require: inScope == kAudioUnitScope_Global InvalidScope /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:408
ca_debug_string: AudioUnitGetProperty: *ioDataSize == 0 on entry /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUDispatch.cpp:178
    PASS
ca_debug_string: AudioUnitGetProperty: *ioDataSize == 0 on entry /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUDispatch.cpp:178
ca_debug_string: AudioUnitGetProperty: *ioDataSize == 0 on entry /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUDispatch.cpp:178
ca_debug_string: AudioUnitGetProperty: *ioDataSize == 0 on entry /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUDispatch.cpp:178
ca_debug_string: AudioUnitGetProperty: *ioDataSize == 0 on entry /Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUDispatch.cpp:178

* * PASS
--------------------------------------------------
VERIFYING SPECIAL PROPERTIES:

VERIFYING CUSTOM UI
Cocoa Views Available: 1
  JUCE_AUCocoaViewClass_6f7c1de6d12b6298
    PASS

HAS FACTORY PRESETS
    ID:   0    Name: Buzcut Bass
    ID:   1    Name: Dark Future Sweep
    ID:   2    Name: Death Toll Bell
    ID:   3    Name: Desert Pipe
    ID:   4    Name: Emperor Chord
    ID:   5    Name: Harpsi
    ID:   6    Name: Mercenary Bass
    ID:   7    Name: Patrol Bass
    ID:   8    Name: Sinister Bass
    ID:   9    Name: Subdue Bass
    ID:  10    Name: Tromba
    ID:  11    Name: Westwood Chime
    ID:  12    Name: Y2180 Strings
    ID:  13    Name: bassdrum

VERIFYING CLASS INFO
    PASS

TESTING HOST CALLBACKS
    PASS

* * PASS
--------------------------------------------------
PUBLISHED PARAMETER INFO:

# # # 32 Global Scope Parameters:
Parameter ID:0
Name: Carrier Wave
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:1
Name: Modulator Wave
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:2
Name: Carrier Frequency Multiplier
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:3
Name: Modulator Frequency Multiplier
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:4
Name: Carrier Attenuation
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:5
Name: Modulator Attenuation
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:6
Name: Tremolo Depth
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:7
Name: Vibrato Depth
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:8
Name: Carrier Tremolo
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:9
Name: Carrier Vibrato
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:10
Name: Carrier Sustain
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:11
Name: Carrier Keyscale Rate
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:12
Name: Modulator Tremolo
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:13
Name: Modulator Vibrato
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:14
Name: Modulator Sustain
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:15
Name: Modulator Keyscale Rate
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:16
Name: Carrier Keyscale Level
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:17
Name: Modulator Keyscale Level
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:18
Name: Algorithm
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:19
Name: Modulator Feedback
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:20
Name: Carrier Attack
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:21
Name: Carrier Decay
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:22
Name: Carrier Sustain Level
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:23
Name: Carrier Release
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:24
Name: Modulator Attack
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:25
Name: Modulator Decay
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:26
Name: Modulator Sustain Level
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:27
Name: Modulator Release
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:28
Name: Carrier Velocity Sensitivity
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:29
Name: Modulator Velocity Sensitivity
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:30
Name: Emulator
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Parameter ID:31
Name: Percussion Mode
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, Readable, Writable 
  -parameter PASS

Testing that parameters retain value across reset and initialization
  PASS

* * PASS
--------------------------------------------------
FORMAT TESTS:

Reported Channel Capabilities (explicit):
      [0, 1]  

No Input, Output Chans:
0-1   0-2   0-4   0-5   0-6   0-7   0-8
X                                         

* * PASS
--------------------------------------------------
RENDER TESTS:

Output Format: AudioStreamBasicDescription:  1 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved
Render Test at 512 frames
Slicing Render Test at 64 frames
  PASS


Render Test at 64 frames, sample rate: 22050 Hz
Render Test at 137 frames, sample rate: 96000 Hz
Render Test at 4096 frames, sample rate: 48000 Hz
Render Test at 4096 frames, sample rate: 192000 Hz
Render Test at 4096 frames, sample rate: 11025 Hz
Render Test at 512 frames, sample rate: 44100 Hz
  PASS

1 Channel Test:
Render Test at 512 frames
  PASS

Bad Max Frames - Render should fail
/Applications/Xcode.app/Contents/Developer/Extras/CoreAudio/AudioUnits/AUPublic/AUBase/AUBase.cpp:1439 inFramesToProcess=8192, mMaxFramesPerSlice=512; TooManyFrames
  from AU (0x810001): 'aumu' 'PwAB' 'Pwve', render err: -10874
  PASS

Checking parameter setting
Using AudioUnitSetParameter
Using AudioUnitScheduleParameter
  PASS

Test MIDI
  PASS

* * PASS
--------------------------------------------------

=== Exited debug console ===
AU VALIDATION SUCCEEDED.
--------------------------------------------------

**Comment by Jeff-Russ** [comment] 2015-02-23 20:24
okay i'm on it.

**Comment by Jeff-Russ** [comment] 2015-02-23 20:36
If my theory is correct. The following will work in Garage Band, putting out audio only in the left channel...

http://bit.ly/1FPNA4h

**Comment by nrezmerski** [comment] 2015-02-23 21:03
No luck... it doesn't load in GB and auval shows this:

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'PwAB' - 'Pwve'
--------------------------------------------------
2015-02-23 15:02:22.971 auvaltool[30261:d07] 15:02:22.970 WARNING:   [0x7fff75e53310] >compload> AudioComponentPluginLoader.cpp:662: RegisterComponentsFromArray: 
Manufacturer String: Plainweave Software
AudioUnit Name: AdlibBlaster
Component Version: 0.11.1 (0xB01)
Component's Bundle Version: 0.0.0

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
2015-02-23 15:02:23.068 auvaltool[30261:d07] Error loading /Library/Audio/Plug-Ins/Components/AdlibBlaster.component/Contents/MacOS/AdlibBlaster:  dlopen(/Library/Audio/Plug-Ins/Components/AdlibBlaster.component/Contents/MacOS/AdlibBlaster, 262): Symbol not found: _OBJC_CLASS_$_NSHTTPURLResponse
  Referenced from: /Library/Audio/Plug-Ins/Components/AdlibBlaster.component/Contents/MacOS/AdlibBlaster
  Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
 in /Library/Audio/Plug-Ins/Components/AdlibBlaster.component/Contents/MacOS/AdlibBlaster
FATAL ERROR: OpenAComponent: result: -50,0xFFFFFFCE

**Comment by Jeff-Russ** [comment] 2015-02-23 22:56
I've pretty much confirmed that the issues is the way different DAW's handle mono AU's. When I made the AU be stereo with nothing in the right channel it worked in every DAW. I think it's best to just avoid mono AU's and make a right channel that just mirrors the left. I don't think this will impact the windows version but If I does, I have a project snapshot taken now, just before I retool it to be "stereo."

**Comment by Jeff-Russ** [comment] 2015-02-25 05:19
Here you go http://jeff-russ.github.io/AdlibBlaster/

**Comment by nrezmerski** [comment] 2015-02-25 06:48
Thanks for the update! However, it makes scratching noises in GB 4, and doesn't show up at all in GB 10. Maybe you can get another GB user to try it?

**Comment by Jeff-Russ** [comment] 2015-02-25 14:07
if GB is like Logic, it cashes versions until there is a name change. Look to see if there is a way to reset and reload.

**Comment by bsutherland** [comment] 2015-11-30 13:17
Nick,

In case you're still interested, I finally merged Jeff's code into the master branch. Hopefully it builds under OSX now.

Cheers,

Bruce

**Comment by Jeff-Russ** [comment] 2015-12-03 18:14
Great!

**Comment by rpazyaquian** [comment] 2016-02-06 19:00
So does this mean this can be built for OSX machines now? Are there instructions for doing so anywhere aside from the comment line here?

**Comment by bsutherland** [comment] 2016-02-07 05:31
Rebecca,

It *should* build under OSX now, but unfortunately I have no way to confirm.

I'm afraid I also can't help much with build instructions, beyond what's in the comments here. If you are able to do it and can contribute instructions, that would be much appreciated!

For help, you could try the Juce forums, or possibly Jeff (who produced the first Mac build here: https://github.com/Jeff-Russ/AdlibBlaster)

Bruce

**Comment by Jeff-Russ** [comment] 2016-02-07 07:16
Everybody: I'm consumed in a web development project at the moment but I plan to return and fix the Mac build as soon as I can. Sorry I've been AWOL!!

**Comment by bsutherland** [comment] 2016-02-07 07:20
Jeff, no worries at all! My day job is web development too..

Thanks a lot for your work getting it working under OSX.

**Comment by Jeff-Russ** [comment] 2016-02-08 04:53
@rpazyaquian 
This is by no stretch a "release" but I had some free time to I fired up Xcode. I just made a few changes and it compiled. It ran with no __major__ issues in OSX 10.10 Logic Pro X and OSX 10.10 Ableton Live 9 as both AUi and VSTi. I _didn't test it very much_ but see if this works for you... 

[Download AUi](https://s3.amazonaws.com/adlibblaster/osx/JuceOPL-vst_Jeff-Russ_build160207.zip)
[Download VSTi](https://s3.amazonaws.com/adlibblaster/osx/JuceOPL-au_Jeff-Russ_build160207.zip)
[my fork of JuceOPLVSTi](https://github.com/Jeff-Russ/AdlibBlaster)

**Comment by bsutherland** [comment] 2016-02-08 22:32
Great, thanks Jeff!

**Comment by gdreyband** [comment] 2017-01-30 01:03
Compiled for Mac this afternoon. Thanks for all the hard work! :)

[JuceOPLVSTi.component.zip](https://github.com/bsutherland/JuceOPLVSTi/files/737971/JuceOPLVSTi.component.zip)

**Comment by bsutherland** [comment] 2017-01-30 12:23
Thanks a lot for building! I'll add it to the release downloads.

Was it hard to build, or did it basically work out of the box?

**Comment by gdreyband** [comment] 2017-01-30 17:35
Pretty much right out of the box in Xcode once I relinked the JUCE plugins correctly.

Minor visual bugs I noticed (not sure if it's on the PC version):
-Selecting a checkbox creates a really noticeable white border around the entire option.
-Clicking on a DDL makes the green box around it disappear until an unrelated area is clicked.

**Comment by bsutherland** [comment] 2019-05-31 01:38
To anyone interested in an OPL plugin for OSX, I recently found out about an excellent project called ADLplug. It is maintained, has builds for Windows and OSX, and does everything which JuceOPLVSTi does and more.

https://github.com/jpcima/ADLplug

**Closed by bsutherland** 2019-05-31 01:38 UTC
Labels: osx, question
