### ISSUE TITLE
Velocity not working correctly.

### ISSUE THREAD

**Issue by Trapezzoid** [bsutherland/JuceOPLVSTi#26] opened 2015-01-21 06:11 UTC
I can't seem to get the latest version to work at all, in Sonar, Reaper and VSThost. 0.10.1 works fine. 

Also, the zip file linked on http://bsutherland.github.io/JuceOPLVSTi gets a 404.

**Comment by bsutherland** [comment] 2015-01-21 06:13
Thanks for the report.
I guess you are downloading from https://github.com/bsutherland/JuceOPLVSTi/releases ?

**Comment by Trapezzoid** [comment] 2015-01-21 06:22
Yeah.

**Comment by bsutherland** [comment] 2015-01-21 06:24
OK, I'll try building it as a 64-bit plugin. I only tested under Renoise under Windows 7.
Do you get any error messages, or is the plugin not recognized?

**Comment by Trapezzoid** [comment] 2015-01-21 06:28
No error messages, just not recognized.

**Comment by bsutherland** [comment] 2015-01-21 06:31
Please try this: https://github.com/bsutherland/JuceOPLVSTi/releases/download/0.11.1/JuceOPLVSTi_x64.zip

**Comment by Trapezzoid** [comment] 2015-01-21 06:45
Seems to work now!
One problem-- upon loading the synth in Sonar, Dosbox mode makes a lot of distorted mess of sound that doesn't stop. ZDoom works perfectly, though. Both modes work fine in VSTHost, so I'm not sure what the problem is.

**Comment by Trapezzoid** [comment] 2015-01-22 03:19
Just noticed another problem. Velocities are getting oddly mixed up. Here's a test showing the audio output (above) and the velocities of the MIDI input:
![an34p](https://cloud.githubusercontent.com/assets/7334303/5849985/57df0d46-a1bb-11e4-983f-2deb6f09b54b.jpg)

**Comment by bsutherland** [comment] 2015-01-23 06:18
Nice plot! I'll take a look.

**Comment by bsutherland** [comment] 2016-10-10 06:45
See also
https://github.com/bsutherland/JuceOPLVSTi/issues/26
https://github.com/bsutherland/JuceOPLVSTi/issues/51

**Comment by bsutherland** [comment] 2017-01-29 02:50
Sorry for so long between updates. I'm a bit stuck on this at the moment. I've checked the functions that calculate attenuation based on velocity, and they seem correct across the range in use.

Velocity values should range from 0 to 127 according to the Juce documentation, and amplitude between 0 and 0x3f (63) according the OPL documentation. I'll keep looking, but pasting here for reference.

![image](https://cloud.githubusercontent.com/assets/169313/22401506/f9cab8aa-e618-11e6-97f1-334da4fe3af7.png)

Once I fix this bug I want to build a new release including your UI changes (again, sorry for taking so long).

**Comment by bsutherland** [comment] 2017-01-29 05:22
Thanks a lot for your patience. Only took me two years, but the bug should be fixed in 0.14.1. Your comment that it worked in 0.10.1 helped me find the cause, thanks a lot.

**Closed by bsutherland** 2017-01-29 05:22 UTC
Labels: bug
