### ISSUE TITLE
panic button

### ISSUE THREAD

**Issue by Moth-Tolias** [bsutherland/JuceOPLVSTi#39] opened 2016-04-16 19:37 UTC
is it at all possible to implement a panic button? sometimes, while under heavy usage, a key will get "stuck" on the sustain, with no way to stop it other than unloading the vst.

**Comment by bsutherland** [comment] 2016-04-17 00:06
Thanks for letting me know.

Panic button sounds like a good temporary measure. Longer term, I'd like to find the cause of the stuck notes. I'll try to reproduce it.

**Comment by bsutherland** [comment] 2018-11-26 13:44
If it can reproduce the issue, it couldn't hurt! Please feel free to upload to this ticket.

**Comment by bsutherland** [comment] 2019-05-31 01:32
I recently found out about an excellent project called ADLplug. It is maintained, and does everything which JuceOPLVSTi does and more. It includes a panic button. In case you're interested:

https://github.com/jpcima/ADLplug

Sorry to say, but I'm closing all enhancement requests on this project, as I don't plan on enhancing it from here on.

**Closed by bsutherland** 2019-05-31 01:32 UTC
Labels: bug, enhancement
