### ISSUE TITLE
Loading an SBI that's already Loaded Crashes the Plugin (and DAW)

### ISSUE THREAD

**Issue by TheGitMagician** [bsutherland/JuceOPLVSTi#55] opened 2017-02-12 01:38 UTC
To reproduce:
-import an SBI file
-import the same SBI file again

==> crash

**Comment by bsutherland** [comment] 2017-02-12 02:08
Thanks for the report! I couldn't reproduce this on my machine, so could you please tell me:

- OS
- DAW
- plugin version
- which SBI file imported
- drag and drop or using "Load .SBI instrument" button?

Thanks!

**Comment by TheGitMagician** [comment] 2017-02-13 09:44
I'm very sorry - I swear the problem was reproducable yesterday (Win 10 x64, Sonar Producer v23, plugin v0.13.4, using the "Load .SBI instrument" button with any of the supplied SBI-files).

However, today whatever I try I can't reproduce the problem ... so, sorry for wasting your time. I'll do some further investigation but as of right now this issue can be closed.

**Comment by bsutherland** [comment] 2017-03-04 03:04
No problem at all! Please let me know if you run into it again. I'll close this for now.

**Closed by bsutherland** 2017-03-04 03:04 UTC
